www/messageboard/urls.py
from django.urls import path
from . import views

app_name = 'msgBoard'
urlpatterns = [
    path('', views.msgboardIndex, name = 'msg'),
]

www/www/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('messageboard.urls'))
]

www/messageboard/models.py
from django.db import models

# Create your models here.

class Msg(models.Model):
    msg_text = models.CharField(max_length=200)
    msg_sender = models.CharField(max_length=64)
    pub_date = models.DateTimeField('date published')
    

www/messageboard/views.py
import datetime
from django.http import HttpResponse, request
from django.shortcuts import render
from django.views import generic
from messageboard.models import Msg
import pytz
import pdb


def msgboardIndex(request):
    latest_msg_list = Msg.objects.order_by('-pub_date')
    if request.method == "POST":
        msg_sender_ip = request.META['REMOTE_ADDR']
        msg_sender = request.POST['msg_sender']
        if msg_sender is not None:
            pass
        else:
            msg_sender = msg_sender_ip
        msg_text = request.POST['msg_text']
        pub_date = datetime.datetime.now(pytz.utc)
        # pdb.set_trace()
        msg = Msg(msg_text = msg_text, msg_sender = msg_sender, pub_date = pub_date)
        msg.save()
        # latest_msg_list.append(Msg(msg_sender, msg_text, pub_date))
    elif request.method == "GET":
        pass
    content = {'latest_msg_list':latest_msg_list}
    return render(request, 'messageboard/msg.html', content)

www/templates/messageboard/msg.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>留言板</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'bootstrap-3.3.7-dist/css/bootstrap.min.css' %}">
    <style type="text/css">
        nav::after {
            content: "";
            clear: both;
        }

        .hello {
            text-align: center;
        }

        body {
            display: block;
            position: relative;
            top: 50px;
        }

        div.msgboxContainer {
            display: block;
            margin-left: 5px;
        }

        .msgbox {
            background: #eeeeee;
            min-height: 100px;
            hyphens: auto;
            padding: 5px;
        }
    </style>
</head>

<body>
    <div class="container">
        <nav class="navbar navbar-fixed-top navbar-inverse" role="navigation">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="#">留言板</a>
            </div>

            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse navbar-collapse">
                <ul class="nav navbar-nav">
                    <li class="active">
                        <a href="#">主页</a>
                    </li>
                    <li>
                        <a href="#">关于</a>
                    </li>
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </nav>
    </div>





    <div class="container">
        <div class="starter-template hello">
            <h1>这是一个留言板</h1>
            <p class="lead">请留言。</p>
        </div>

        <div class="row">
            <div class="col-md-6  col-md-offset-3">

                <div class="msgboxContainer">
                    {% if latest_msg_list %}
                    <ul class="media-list">
                        {% for msg in latest_msg_list %}
                        <li class="media">
                            <!-- <div class="media-left">
                                <a href="#">
                                    <img class="media-object" src="#" alt="#">
                                </a>
                            </div> -->
                            <div class="media-body msgbox" >
                                    <h4 class="media-heading">{{ msg.msg_sender }}</h4>
                                    <P>{{ msg.msg_text }} </P>
                            </div>
                        </li>
                        {% endfor %}
                    </ul>
                    {% else %}
                    <p>没有留言.</p>
                    {% endif %}
                </div>
            </div>
        </div>
        <hr>

        <div class="form-group">
            <div class="msginput col-md-6 col-md-offset-3">
                <form action="{% url 'msgBoard:msg' %}" name="msg_form" method="post" role="form">
                        {% csrf_token %}
                    <div class="row " style="margin-bottom: 10px;">
                        <div>
                            <div class="col-md-12 col-xs-12 form-group has-warning ">
                                <label for="msg_sender">用户名（选填）：</label>
                                <input type="text" name="msg_sender" id="msg_sender" class=" form-control">
                            </div>
                        </div>

                    </div>
                    <div class="row form-group">
                        <div class="col-md-12">
                                 <textarea name="msg_text" id="msg_text" cols=rows="20" class="form-control " style="resize: vertical;height: 100px;"></textarea>
                        </div>
                    </div>
                    <div class="row form-group">
                        <div class="col-md-3">
                            <input type="submit" value="submit" class="btn btn-default">
                        </div>

                    </div>

                </form>

            </div>

        </div>

    </div>
    <footer class="footer-content">

    </footer>

    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://cdn.bootcss.com/jquery/3.3.1/jquery.min.js"></script>
    <script>window.jQuery || document.write('<script src="../../assets/js/vendor/jquery.min.js"><\/script>')</script>
    <script src="{% static 'bootstrap-3.3.7-dist/js/bootstrap.min.js' %}"></script>
</body>

</html>